#!/bin/sh
set -e

mkdir -p /tmp/pkgs
cd /tmp/pkgs

# Add the sources and keys
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
sudo tee /etc/apt/sources.list.d/nvidia-docker.list

# Update sources
sudo apt-get update

# Install nvidia-docker and reload docker daemon configurations
sudo apt-get install -y nvidia-docker2
sudo pkill -SIGHUP dockerd

rm -rf /tmp/pkgs
cd $HOME
echo "nvidia-docker installed successfully !"
